Why Numpy & Pandas?
介绍两个科学运算当中最为重要的两个模块，一个是 numpy,一个是 pandas。任何关于数据分析的模块都少不了它们两个。

应用
数据分析、机器学习、深度学习

为什么使用 numpy & pandas?
运算速度快：numpy 和 pandas 都是采用 C 语言编写, pandas 又是基于 numpy, 是 numpy 的升级版本。
消耗资源少：采用的是矩阵运算，会比 python 自带的字典或者列表快好多。

使用 python 3+:
pip3 install numpy

使用 python 3+:
pip3 install pandas

In [1]:
import numpy as np 
array=np.array([[1,2,3],[2,3,4]])  # 2row & 3column

In [2]:
print(array)

print('number of dim:',array.ndim)  # ndim维度

[[1 2 3]
 [2 3 4]]
number of dim: 2


In [3]:
print('shape :',array.shape)    # shape行数和列数，array.shape=array的形狀

print('size:',array.size)   # size元素个数

shape : (2, 3)
size: 6


# Numpy 的创建 array

array：创建数组
dtype：指定数据类型
zeros：创建数据全为0
ones：创建数据全为1
empty：创建数据接近0
arrange：按指定范围创建数据
linspace：创建线段

In [4]:
a = np.array([2,23,4])  # list 1d
print(a)

[ 2 23  4]


In [5]:
a = np.array([2,23,4], dtype=np.int)
print(a.dtype)

int32


In [6]:
a = np.array([2,23,4], dtype=np.int32)
print(a.dtype)

int32


In [7]:
a = np.array([2,23,4], dtype=np.float)
print(a.dtype)

float64


In [8]:
a = np.array([2,23,4], dtype=np.float32)
print(a.dtype)

float32


In [9]:
a = np.array([[2,23,4],[2,32,4]])  # 2d矩阵 2row&3column
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [10]:
a = np.zeros((3,4)) # 数据全为0，3行4列
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
a = np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
a=np.empty((3,4))  #数据为empty，创建全空数组, 其实每个值都是接近于零的数
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a=np.arange(10,20,2) # arange连续数组，10-19 的数据，2步长，自行設定頭尾數值
print(a)

[10 12 14 16 18]


In [14]:
a=np.arange(12).reshape((3,4)) # 建構3行4列，0到11，固定從0開始，reshape重朔
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
a=np.linspace(1,10,20)    ## 开始端1，结束端10，且分割成20个数据，生成线段
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [16]:
a=np.linspace(1,10,6).reshape((2,3)) #linespace切6段= reshape的2*3=6
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [18]:
a = np.linspace(1,10,20).reshape((5,4)) # 更改shape
print(a)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


# Numpy 基础运算1

## 一維陣列计算

In [19]:
import numpy as np
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
print(a)
print(b)

[10 20 30 40] [0 1 2 3]
[10 20 30 40]
[0 1 2 3]


In [20]:
c=a-b
print(c)

[10 19 28 37]


In [21]:
print(b)
d=b**2
print(d)

[0 1 2 3]
[0 1 4 9]


In [22]:
c=10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [23]:
c=10*np.cos(a)
print(c)

[-8.39071529  4.08082062  1.5425145  -6.66938062]


In [24]:
print(b)
print(b < 3)
print(b == 3)

[0 1 2 3]
[ True  True  True False]
[False False False  True]


## 多行多维度的矩阵计算

In [25]:
import numpy as np
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
c=a*b                      
print(a)
print(b)
print(c)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]


### Numpy中的矩阵乘法分为两种， 其一是前文中的对应元素相乘，其二是标准的(np.dot)矩阵乘法运算，即对应行乘对应列得到相应元素

In [26]:
c_dot=np.dot(a,b)
print(c_dot)

[[2 4]
 [2 3]]


In [27]:
c_dot_2=a.dot(b) 
print(c_dot_2)

[[2 4]
 [2 3]]


In [28]:
import numpy as np
a=np.random.random((2,4)) #2*4 random隨機亂數
print(a) 

[[0.65359809 0.73323962 0.36721798 0.58957939]
 [0.29933927 0.97585422 0.1274911  0.59713596]]


In [29]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))

4.343455639744083
0.12749110408821995
0.9758542221174762


In [30]:
print("a =",a)

a = [[0.65359809 0.73323962 0.36721798 0.58957939]
 [0.29933927 0.97585422 0.1274911  0.59713596]]


### 对矩阵中所有元素进行求和，寻找最小值，寻找最大值

In [31]:
print("sum =",np.sum(a,axis=1)) #axis=1以"行"作为查找单元
print("min =",np.min(a,axis=0)) #axis=0以"列"作为查找单元
print("max =",np.max(a,axis=1)) 

sum = [2.34363508 1.99982056]
min = [0.29933927 0.73323962 0.1274911  0.58957939]
max = [0.73323962 0.97585422]


# Numpy 基础运算2

## argmin() 和 argmax() 两个函数分别对应着求矩阵中最小元素和最大元素的索引。

In [32]:
import numpy as np
#对应元素的索引
A=np.arange(2,14).reshape((3,4))
print(A)
print(np.argmin(A))  # argmin=2=A[0]
print(np.argmax(A))  # argmax=13=A[11]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11


In [33]:
print(A)
print(np.mean(A))       #同print(A.mean())
print(np.average(A))
print(np.median(A))

print(np.cumsum(A))     #cumsum()累加函数

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [34]:
print(A)       # 3行4列矩阵
print(np.diff(A))      #diff()矩陣累差函数，3行3列的矩阵

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [35]:
print(A)
print(np.nonzero(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [36]:
A=np.arange(14,2,-1).reshape((3,4)) #from 14 to 2 and reshape3*4 array
print(A)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [37]:
print(np.sort(A)) #row orderby ASC

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


## 矩阵转置 transpose (row and column方向互換)

In [38]:
print(A)
print(np.transpose(A))   # print(A.T)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [39]:
print((A.T).dot(A))

[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


### clip(Array,Array_min,Array_max)

In [42]:
print(A)
print(np.clip(A,5,9))   #同print(A.clip(5,9))，矩陣中的值大於9變成9，小於5變成5

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [43]:
print(A)
print(np.mean(A,axis=0)) #axis=0,imply column cal

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[10.  9.  8.  7.]


In [44]:
print(A)
print(np.mean(A,axis=1)) #axis=1,imply row cal

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[12.5  8.5  4.5]


# Numpy 索引

## 一维矩阵索引(索引值從0開始)

In [45]:
import numpy as np

A=np.arange(3,15)
print(A)
print(A[3])  #python索引值從0開始,A[0]=3

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


## 二维矩阵索引(索引值從0開始)

In [49]:
A=np.arange(3,15).reshape((3,4))
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [50]:
print(A[2]) 
print(A[2][1])   #同print(A[2,1])
print(A[2,1])

[11 12 13 14]
12
12


In [51]:
print(A[2,:])    #Second row all number


[11 12 13 14]


In [53]:
print(A[:,1])  #First column all number
print(A[1,1:3])

[ 4  8 12]
[8 9]


In [54]:
for row in A:
	print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [55]:
for column in A.T:
	print(column)  #imply print(A.T)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [56]:
A=np.arange(3,15).reshape((3,4))
print(A)
print(A.flatten())   #flatten把n维的矩阵平坦成1行的数列

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [57]:
for item in A.flat:
	print(item)    #把array平坦化 only one column

3
4
5
6
7
8
9
10
11
12
13
14


# Numpy array 合并

## np.vstack()上下合并與np.hstack() 左右合并

In [68]:
import numpy as np
A=np.array([1,1,1])
B=np.array([2,2,2])

print(A.shape)
print(np.vstack((A,B))) 

#vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作

(3,)
[[1 1 1]
 [2 2 2]]


In [69]:
C=np.vstack((A,B))
print(C)
print(A.shape,C.shape)
#A仅仅是一个拥有3项元素的数组（数列），而合并后得到的C是一个2行3列的矩阵。

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)


In [70]:
D=np.hstack((A,B))   # horizontal stack，D本身為A，B两个数列的左右合并
print(D)             # 新生成的D本身也是一个含有6项元素的序列
print(A.shape,D.shape) 

[1 1 1 2 2 2]
(3,) (6,)


## np.newaxis()

In [71]:
print(A)
print(A[np.newaxis,:]) #對A增加一個row維度

[1 1 1]
[[1 1 1]]


### 将具有3个元素的array转换为了1行3列以及3行1列的矩阵

In [72]:
print(A)
print(A[:,np.newaxis]) #對A增加一個column維度

[1 1 1]
[[1]
 [1]
 [1]]


In [73]:
import numpy as np
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack

In [74]:
print(D)
print(A.shape,D.shape)

[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


## np.concatenate()
### 当你的合并操作需要针对多个矩阵或序列时，借助concatenate函数可能会让你使用起来比前述的函数更加方便

In [75]:
C=np.concatenate((A,B,B,A),axis=0)  #同print(np.hstack((A,A,B)))
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [76]:
D=np.concatenate((A,B,B,A),axis=1)
print(D)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


# Numpy array 分割

In [77]:
#创建数据，建立3行4列的Array
import numpy as np

A=np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 纵向分割與横向分割

In [78]:
#纵向分割，從中央把一個array分割成兩個array，並用row方式組合為兩個一組
print(np.split(A,2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [79]:
#横向分割 ，從橫向切割把一個array切割成3個array
print(np.split(A,3,axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [80]:
#错误的分割 
print(np.split(A, 3, axis=1))

#ValueError: array split does not result in an equal division

ValueError: array split does not result in an equal division

In [81]:
#不等量的分割
print(A)
print(np.array_split(A, 3, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [82]:
#其他的分割方式
print(np.vsplit(A,3)) #分割成三塊

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [83]:
print(np.hsplit(A,2)) #分割成兩塊

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# Numpy copy & deep copy

In [84]:
import numpy as np

a=np.arange(4)
print(a)

[0 1 2 3]


In [85]:
b = a
c = a
d = b

### 改变a的第一个值，b、c、d的第一个值也会同时改变。

In [86]:
a[0] = 11
print(a)

[11  1  2  3]


In [87]:
b is a   #check b == a array # True
c is a	  # True
d is a		# True

True

In [88]:
#同样更改d的值，a、b、c也会改变。
d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)            # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


### copy() 的赋值方式没有关联性

In [89]:
b=a.copy()      #deep copy
print(b)        

[11 22 33  3]


In [90]:
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])
       #此时a与b已经没有关联。

[11 22 33 44]
[11 22 33  3]
